### ISSUE TITLE
"Show this thread" is hidden

### ISSUE THREAD

**Issue by cmdrfletcher** [dangeredwolf/ModernDeck#166]
I don't know if it is intended, but I like to see the info "Show this thread" beneath the tweets.

I help myself with the following customs CSS. Maybe you can implement a switch for the user to choose.

```css
.js-show-this-thread {
	display: inherit;
	color:var(--retweetColor)!important;
	text-align:center;
}
```
Keep up the good work!

Patrick
